spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rocketFeed?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rhdwnsla1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    multipart:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
